MIME-Version: 1.0
x-no-auto-attachment: 1
Received: by 10.100.180.34; Wed, 28 Feb 2018 11:48:55 -0800 (PST)
Date: Wed, 28 Feb 2018 11:48:55 -0800
Message-ID: <CANQV6ako3mG2mpXzySJsO99mVABbxx6Q4_ryCY2RfdYeD8TBEQ@mail.gmail.com>
Subject: Stay more organized with Gmail's inbox
From: Gmail Team <mail-noreply@google.com>
To: Krzydxtof nowak <ehodowcatest@gmail.com>
Content-Type: multipart/alternative; boundary="f403045ee93a8c315405664b0815"

--f403045ee93a8c315405664b0815
Content-Type: text/plain; charset="UTF-8"
Content-Transfer-Encoding: quoted-printable

 Stay more organized with Gmail's inbox
[image: Google]

Hi Krzydxtof

Gmail's inbox puts you in control

[image: Inbox video] <https://www.youtube.com/watch?v=3DCFf7dlewJus>
Meet the inbox

Gmail's inbox sorts your email into categories so you can see what's new at
a glance, decide which emails you want to read when and view similar types
of emails together. Watch the video
<https://www.youtube.com/watch?v=3DCFf7dlewJus>
[image: Social tab]
Choose your categories

The Social and Promotions categories are on by default. Add categories like
Updates and Forums or remove categories to have those emails show up in
your Primary inbox. Learn how to choose categories
<https://support.google.com/mail/?hl=3Den&p=3Dinboxcategories_all>
[image: Customize]
Customize your inbox

If you see a message you want in a different category, you can move it
there. On mobile devices, you can even choose which categories create a
notification. More customization tips
<https://support.google.com/mail/?hl=3Den&p=3Dinboxcategories_all>



To learn more about Gmail's inbox, check out the help center
<https://support.google.com/mail/?hl=3Den&p=3Dinboxcategories_all> or watch=
 the
video <https://www.youtube.com/watch?v=3DCFf7dlewJus&amp>.


[image: Gmail icon] Happy emailing,
The Gmail Team
=C2=A9 2018 Google Inc. 1600 Amphitheatre Parkway, Mountain View, CA 94043

--f403045ee93a8c315405664b0815
Content-Type: text/html; charset="UTF-8"
Content-Transfer-Encoding: quoted-printable

<!DOCTYPE html>
<html><head><meta http-equiv=3D"content-type" content=3D"text/html;charset=
=3DUTF-8"/><title>Stay more organized with Gmail&#39;s inbox</title></head>=
<body style=3D"background-color:#e5e5e5; margin:20px 0;"><br/><div style=3D=
"margin:2%;"><div style=3D"direction:ltr; text-align:left; font-family:'Ope=
n sans','Arial',sans-serif; color:#444; background-color:white; padding:1.5=
em; border-radius:1em; box-shadow:1px -5px 8px 2px #bbb; max-width:580px; m=
argin:2% auto 0 auto;"><table style=3D"background:white;width:100%"><tr><td=
><div style=3D"width:90px; height:54px; margin:10px auto;"><img src=3D"http=
s://services.google.com/fh/files/emails/google_logo_flat_90_color.png" alt=
=3D"Google" width=3D"90" height=3D"34"/></div><div style=3D"width:90%; padd=
ing-bottom:10px; padding-left:15px"><p><img alt=3D"" aria-hidden=3D"true" s=
rc=3D"https://ssl.gstatic.com/ui/v1/icons/mail/images/gmail_logo_large.png"=
 style=3D"display:inline-block; max-height:10px; margin-right:5px;"/><span =
style=3D"font-family:'Open sans','Arial',sans-serif; font-weight:bold; font=
-size:small; line-height:1.4em">Hi Krzydxtof</span></p><p><span style=3D"fo=
nt-family:'Open sans','Arial',sans-serif; font-size:2.08em;">Gmail&#39;s in=
box puts you in control</span><br/></p></div><p></p><div style=3D"clear:bot=
h; float:left; padding: 0px 5px 10px 10px; vertical-align:top;"><a href=3D"=
https://www.youtube.com/watch?v=3DCFf7dlewJus" style=3D"text-decoration:non=
e; border:0;"><img alt=3D"Inbox video" width=3D"129" height=3D"129" style=
=3D"border:0" src=3D"https://ssl.gstatic.com/mail/welcome/localized/en/welc=
ome_video_2.png"/></a></div><div style=3D"float:left; vertical-align:middle=
; padding:10px; max-width:398px; float:left;"><table style=3D"vertical-alig=
n:middle;"><tr><td style=3D"font-family:'Open sans','Arial',sans-serif;"><s=
pan style=3D"font-size:20px;">Meet the inbox</span><br/><br/><span style=3D=
"font-size:small; line-height:1.4em">Gmail's inbox sorts your email into ca=
tegories so you can see what's new at a glance, decide which emails you wan=
t to read when and view similar types of emails together. <a href=3D"https:=
//www.youtube.com/watch?v=3DCFf7dlewJus" style=3D"text-decoration:none; col=
or:#15C">Watch the video</a></span></td></tr></table></div><div style=3D"fl=
oat:left; clear:both; padding:0px 5px 10px 10px;"><img src=3D"https://ssl.g=
static.com/mail/welcome/localized/en/welcome_inbox_tab_2.png" alt=3D"Social=
 tab" style=3D"display:block;" width=3D"129" height=3D"129"/></div><div sty=
le=3D"float:left; vertical-align:middle; padding:10px; max-width:398px; flo=
at:left;"><table style=3D"vertical-align:middle;"><tr><td style=3D"font-fam=
ily:'Open sans','Arial',sans-serif;"><span style=3D"font-size:20px;">Choose=
 your categories</span><br/><br/><span style=3D"font-size:small; line-heigh=
t:1.4em">The Social and Promotions categories are on by default. Add catego=
ries like Updates and Forums or remove  categories to have those emails sho=
w up in your Primary inbox. <a href=3D"https://support.google.com/mail/?hl=
=3Den&amp;p=3Dinboxcategories_all" style=3D"text-decoration:none; color:#15=
C">Learn how to choose categories</a></span></td></tr></table></div><div st=
yle=3D"float:left; clear:both; padding:0px 5px 10px 10px;"><img src=3D"http=
s://ssl.gstatic.com/mail/welcome/localized/en/welcome_customize_2.png" alt=
=3D"Customize" style=3D"display:block;" width=3D"129" height=3D"129"/></div=
><div style=3D"float:left; vertical-align:middle; padding:10px; max-width:3=
98px; float:left;"><table style=3D"vertical-align:middle;"><tr><td style=3D=
"font-family:'Open sans','Arial',sans-serif;"><span style=3D"font-size:20px=
;">Customize your inbox</span><br/><br/><span style=3D"font-size:small; lin=
e-height:1.4em">If you see a message you want in a different category, you =
can move it there. On mobile devices, you can even choose which categories =
create a notification. <a href=3D"https://support.google.com/mail/?hl=3Den&=
amp;p=3Dinboxcategories_all" style=3D"text-decoration:none; color:#15C">Mor=
e customization tips</a></span></td></tr></table></div><br/><br/><br/><div =
style=3D"clear: both; vertical-align:middle; padding-left:15px; line-height=
:1.4em; font-family:'Open sans','Arial',sans-serif; font-size: small; text-=
align: left">To learn more about Gmail's inbox, check out the <a href=3D"ht=
tps://support.google.com/mail/?hl=3Den&amp;p=3Dinboxcategories_all" style=
=3D"text-decoration:none; color:#15C">help center</a> or <a href=3D"https:/=
/www.youtube.com/watch?v=3DCFf7dlewJus&amp" style=3D"text-decoration:none; =
color:#15C">watch the video</a>.</div><br/><br/>
<div style=3D"clear:both; padding-left:13px; height:6.8em;"><table style=3D=
"width:100%; border-collapse:collapse; border:0"><tr><td style=3D"width:68p=
x"><img alt=3D'Gmail icon' width=3D"49" height=3D"37" src=3D"https://ssl.gs=
tatic.com/ui/v1/icons/mail/images/gmail_logo_large.png" style=3D"display:bl=
ock;"/></td><td style=3D"align:left; font-family:'Open sans','Arial',sans-s=
erif; vertical-align:bottom"><span style=3D"font-size:small">Happy emailing=
,<br/></span><span style=3D"font-size:x-large; line-height:1">The Gmail Tea=
m</span></td></tr></table></div>
</td></tr></table></div>
<div style=3D"direction:ltr;color:#777; font-size:0.8em; border-radius:1em;=
 padding:1em; margin:0 auto 4% auto; font-family:'Arial','Helvetica',sans-s=
erif; text-align:center;">=C2=A9 2018 Google Inc. 1600 Amphitheatre Parkway=
, Mountain View, CA 94043<br/></div></div></body></html>

--f403045ee93a8c315405664b0815--
